### ISSUE TITLE
Why the dispatch button cannot be clicked?

### ISSUE THREAD

**Issue by phoenixg** [llaski/nova-scheduled-jobs#10]
how can this button work?

**Comment by llaski** [comment]
The button can only be clicked for scheduled jobs with their own Job Classes. We just pushed an update to disable the dispatch button if it's not available for a scheduled job.

**Comment by phoenixg** [comment]
Sorry, what do you mean by own job classes?

**Comment by llaski** [comment]
@phoenixg Typically a job class that exists in the jobs folder. It can probably also just be any class, but it needs to be resolvable out of the IOC container.

**Comment by phoenixg** [comment]
@llaski How to make a job that can be dispatched online?

**Comment by nikhilbaby2000** [comment]
@phoenixg I was stumbled upon this. You can find what they meant here:

\Llaski\NovaScheduledJobs\Http\Controllers\DispatchJobController::create
\Llaski\NovaScheduledJobs\Rules\JobExist

The JobExist Rule checks if the the stuff is a Job by simply checking if the passed value can be resolved as a class: `class_exists($value) && strpos($value, '\Jobs') !== false`

I was looking to run an artisan command form Nova panel. This is not possible at the moment, because this Package is only for Jobs.

But it could be improved, as the package is picking up anything that's Scheduled in Kernel.

You can update here [To Enable the Commands as dispatch-able ]
/vendor/llaski/nova-scheduled-jobs/resources/js/components/Tool.vue:canDispatchCommand

```
canDispatchCommand(command) {
            if(command){
                return true;
            }

            return false;
        }
```

You can update here [To Run commands]: 
\Llaski\NovaScheduledJobs\Http\Controllers\DispatchJobController::create 
with: >> 
```
public function create(Request $request)
    {
        $command = array_first(explode(' ', $request->get('command')));

        if (in_array($command, array_keys(Artisan::all()))) {
            return command($command);
        }

        $data = $request->validate([
            'command' => ['required', 'string', new JobExist]
        ]);

        $command = resolve($data['command']);

        dispatch($command);
    }
```

But it wouldn't be the right way to edit in a vendor code.
I would suggest you to fork it.

**Comment by babul** [comment]
@nikhilbaby2000 Thank you for your write up, that is most helpful!

**Comment by oleksandr-roskovynskyi** [comment]
Did you manage to solve the problem? In my class, everything seems to meet the requirements, but the button is not active
